apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-deployment
  labels:
    app: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: bitnami/sonarqube:9.9.6-debian-12-r4
        ports:
        - containerPort: 9000
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        env:
        - name: SONAR_JDBC_URL
          value: jdbc:postgresql://postgresql:5432/sonarqube
        - name: SONARQUBE_DATABASE_PASSWORD
          value: sonarqube
      # nodeSelector:
      #           role: worker


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: bitnami/postgresql:15.7.0
        env:
        - name: POSTGRES_DB
          value: sonarqube
        - name: POSTGRES_USER
          value: bn_sonarqube
        - name: POSTGRESQL_PASSWORD
          value: sonarqube
        ports:
        - containerPort: 5432
      # nodeSelector:
      #           role: worker
