apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-deployment
  labels:
    app: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:community
        ports:
        - containerPort: 9000
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        env:
        - name: SONAR_JDBC_URL
          value: jdbc:postgresql://postgresql:5432/sonarqube
        - name: SONAR_JDBC_USERNAME
          value: sonarqube
        - name: SONAR_JDBC_PASSWORD
          value: sonarqube
        volumeMounts:
        - name: sonarqube-storage
          mountPath: /opt/sonarqube/data
        volumes:
        - name: sonarqube-storage
          persistentVolumeClaim:
            claimName: sonarqube-pvc
        #   valueFrom:
        #     configMapKeyRef:
        #       name: sonarqube-config
        #       key: SONARQUBE_JDBC_URL
        # - name: SONARQUBE_DATABASE_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: sonarqube-db-creds
        #       key: SONARQUBE_DATABASE_PASSWORD
      # nodeSelector:
      #           role: worker


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:14
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: sonarqube
        - name: POSTGRES_USER
          value: sonarqube
        - name: POSTGRES_PASSWORD
          value: sonarqube
        volumeMounts:
        - name: postgresql-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgresql-storage
        persistentVolumeClaim:
          claimName: posgresql-pvc
        # - name: POSTGRES_USER
        #   valueFrom:
        #    secretKeyRef:
        #       name: sonarqube-db-creds
        #       key: POSTGRES_USER

        # - name: POSTGRESQL_PASSWORD
        #   valueFrom:
        #    secretKeyRef:
        #       name: sonarqube-db-creds
        #       key: POSTGRESQL_PASSWORD
        ports:
        - containerPort: 5432
      # nodeSelector:
      #           role: worker
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi