# apiVersion: v1
# kind: Service
# metadata:
#   namespace: dev-argocd
#   name: sonarqube
# spec:
#   selector:
#     app: sonarqube
#   ports:
#   - protocol: TCP
#     port: 9000
#     targetPort: 9000
#   type: LoadBalancer

apiVersion: v1
kind: Service
metadata:
  namespace: dev-argocd
  name: sonarqube
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: sonarqube

---

# apiVersion: v1
# kind: Service
# metadata:
#   name: sonarqube-postgresql
#   labels:
#     app: sonarqube-postgresql
#   spec:
#     type: NodePort
#     ports:
#      - port: 5432
#     selector:
#       app: sonarqube-postgresql

apiVersion: v1
kind: Service
metadata:
  namespace: dev-argocd
  name: postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432 
  selector:
    app: postgresql